### ISSUE TITLE
Savings Dai Rate Provider Review - Gnosis Chain

### ISSUE THREAD

**Issue by Zen-Maxi** [threerocks-defi/code-review#24]
### Type of Smart Contract

Rate Provider

### Contract Source Code

https://gnosisscan.io/address/0x89c80a4540a00b5270347e02e2e144c71da2eced#readContract

### Protocol Documentation

https://docs.makerdao.com/build/dai.js/savingsservice

### Protocol Audits

https://github.com/makerdao/sdai/blob/0377fa3a3e8af846f7511fb7cfe18c2e276e9dfa/audits/ChainSecurity_Oazo_Apps_Limited_Savings_Dai_audit_1.pdf

### Terms and Conditions

- [X] The protocol to be integrated has been audited by at least one security firm or independent researcher.
- [X] If deployed, the contract is verified on etherscan.
- [X] The contract does not rely upon an EOA to supply any critical data (e.g., price).
- [X] If upgradeable, the contract's administrator is not an EOA.

**Comment by rabmarut** [comment]
@Zen-Maxi Who developed this? I'd like to chat with them about one small detail.

The rate provider is called `ERC4626RateProvider` and seems to be intended as a general-purpose rate provider for ERC-4626 tokens. It _almost_ works for that use case, except that it doesn't account for underlying token decimals.

It happens to work in this specific case because the underlying token (WXDAI) has 18 decimals, but I want to make sure I'm not approving something that is intended to be used for other tokens in the future.

**Comment by Zen-Maxi** [comment]
@rabmarut added you to a TG chat with the gnosis and angle guys who deployed the rate provider. Feel free to discuss with them as needed.
